### ISSUE TITLE
Can't runnning web application

### ISSUE THREAD

**Issue by tracertping** [JPCERTCC/LogonTracer#6]
Error
[*] Script start. 2017/12/08 16:20:49
[!] Can't runnning web application.
when running python3 logontracer.py -r -o 8080 -u neo4j -p password -s localhost

**Comment by swappage** [comment]
Hi,
appearently the problem is that the port is not casted to int and this causes app.run() to fail.

If you don't mind binding the server to a different port, you can hardcode the value 8080 at line 484

changing the line to:

app.run(host="0.0.0.0", port=8080)

i cant do a pull request to fix the problem as of now, maybe sometime later. but this quick fix should at least allow you to run the application.

**Comment by shu-tom** [comment]
Fixed the port value str to int. 72d6ea804c611b21eeadd13821232815dbe61841
Please run this fix version.
